# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_project(object):
    def setupUi(self, Add_project):
        Add_project.setObjectName("Add_project")
        Add_project.resize(828, 116)
        self.buttonBox = QtWidgets.QDialogButtonBox(Add_project)
        self.buttonBox.setGeometry(QtCore.QRect(480, 80, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tableWidget = QtWidgets.QTableWidget(Add_project)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 810, 69))
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    border-style: none;\n"
"    border-bottom: 1px solid black;\n"
"    border-right: 1px solid black;\n"
"}\n"
"QTableWidget {gridline-color: black;}\n"
"")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)

        self.retranslateUi(Add_project)
        self.buttonBox.accepted.connect(Add_project.accept)
        self.buttonBox.rejected.connect(Add_project.reject)
        QtCore.QMetaObject.connectSlotsByName(Add_project)

    def retranslateUi(self, Add_project):
        _translate = QtCore.QCoreApplication.translate
        Add_project.setWindowTitle(_translate("Add_project", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Add_project", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Add_project", "Project name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Add_project", "Start"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Add_project", "Finish"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Add_project", "Color"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
